# :schema node_modules/wrangler/config-schema.json
name = "cloud-calendar"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "dist"
compatibility_date = "2024-09-21"

[[d1_databases]]
binding = "DB"
database_name = "ita-web-d1"
database_id = "d1-database-id"
preview_database_id = "DB"
migrations_dir = "./prisma/migrations"
